# Generated by Django 5.1.2 on 2024-10-17 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Особенность')),
                ('description', models.CharField(max_length=256, null=True, verbose_name='Описание особенности')),
            ],
            options={
                'verbose_name': 'Особенность',
                'verbose_name_plural': 'Особенности',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Язык программирования')),
            ],
            options={
                'verbose_name': 'Язык программирования',
                'verbose_name_plural': 'Языки программирования',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Технология')),
                ('description', models.CharField(max_length=256, null=True, verbose_name='Описание технологии')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название проекта')),
                ('description', models.CharField(max_length=512, verbose_name='Описание проекта')),
                ('created_at', models.DateField(verbose_name='Дата создания проекта')),
                ('type', models.CharField(choices=[('test', 'Тестовый проект'), ('pet', 'Pet проект'), ('template', 'Шаблон проекта')], default='pet', max_length=64, verbose_name='Тип проекта')),
                ('git_url', models.URLField(null=True, unique=True, verbose_name='Ссылка на GitHub')),
                ('pc_url', models.FilePathField(allow_files=False, allow_folders=True, unique=True, verbose_name='Ссылка на папку проекта')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор проекта')),
                ('features', models.ManyToManyField(to='catalogue.feature', verbose_name='Особенности проекта')),
                ('languages', models.ManyToManyField(to='catalogue.language', verbose_name='Используемый язык программирования')),
                ('technologies', models.ManyToManyField(to='catalogue.technology', verbose_name='Используемая технология')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
