# Generated by Django 5.1.2 on 2024-10-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_feature_name_alter_language_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание особенности'),
        ),
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='catalogue.feature', verbose_name='Особенности проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='git_url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Ссылка на GitHub'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pc_url',
            field=models.CharField(max_length=512, unique=True, verbose_name='Ссылка на папку проекта'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание технологии'),
        ),
    ]
