# Generated by Django 5.1.2 on 2024-11-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_link_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название ссылки'),
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('OFFICIAL', 'Официальная документация'), ('API', 'Api'), ('TEMPLATES', 'Шаблоны'), ('FONTS', 'Шрифты'), ('PICS', 'Обои, иконки и аватарки'), ('MODIFY', 'Проверка и редактирование'), ('HOSTING', 'Хостинг'), ('TIPS', 'Шпаргалки и советы'), ('PRACTICE', 'Практика'), ('EXAMPLES', 'Примеры'), ('INTERVIEW', 'Для собеседования'), ('OTHER', 'Разное')], default='OFFICIAL', max_length=64, verbose_name='Тип ссылки'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('TEST', 'Тестовый проект'), ('PET', 'Пет-проект'), ('TEMPLATE', 'Шаблон проекта'), ('SCHOOL', 'Учебный проект'), ('COMMERCIAL', 'Коммерческий проект')], default='PET', max_length=64, verbose_name='Тип проекта'),
        ),
    ]
