# Generated by Django 5.1.2 on 2024-11-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_link_name_alter_link_type_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('OFFICIAL', 'Официальная документация'), ('API', 'Api'), ('TEMPLATES', 'Шаблоны'), ('FONTS', 'Шрифты'), ('PICS', 'Обои, иконки и аватарки'), ('MODIFY', 'Проверка и редактирование'), ('HOSTING', 'Хостинг'), ('TIPS', 'Шпаргалки и советы'), ('PRACTICE', 'Практика'), ('EXAMPLES', 'Примеры'), ('INTERVIEW', 'Для собеседования'), ('VIDEO', 'Видео материалы'), ('OTHER', 'Разное')], default='OFFICIAL', max_length=64, verbose_name='Тип ссылки'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='Unique constraint'),
        ),
    ]
