# Generated by Django 5.1.2 on 2024-12-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_link_important_alter_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Важная ссылка?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='catalogue.technology', verbose_name='Используемая технология'),
        ),
    ]
